#!/bin/env bash
# vim: expandtab ts=2 sw=2
# (Reminder: Don't forget to run './rem-chtest1 all' in ./reminders)
# (It won't work well to run it from here.)

t=test
tests="$t/add-change-delete-etc-101 $t/add-change-delete-etc-102"
tests="$tests $t/attachments-101 $t/references-101 $t/new-task-101"
tests="$tests $t/chparent-101 $t/chhandle-101 $t/clear-desc-101"

status=0
testcount=0
failures=0
stodo settings
for f in $tests; do
  echo "=============== Executing $f ==============="
  if $f; then
    echo "$f Succeeded."
  else
    echo "$f FAILED."
    status=99
    ((++failures))
  fi
  ((++testcount))
  echo "============== (Completed $f) =============="
done
if [ $status = 0 ]; then
  echo "All tests SUCCEEDED."
else
  echo "$failures (out of $testcount) tests FAILED."
fi
exit $status
