#!/bin/bash
# vim: ts=2 sw=2 expandtab
# Note: depends on $stodo_envpath being initialized.

set_rubylib() {
  clsrv=client_server
  clntd=$clsrv/client
  dirlist="facility error configuration notification specs data"
  dirlist="$dirlist coordination util attributes"
  dirlist="$dirlist domain/services/reporting external/messaging"
  dirlist="$dirlist lib/messaging domain/support"
  dirlist="$dirlist lib/util lib/util/redis external/util"
  dirlist="$dirlist $clsrv/support $clsrv/communication $clntd/main"
  dirlist="$dirlist $clsrv/structural $clsrv/facility $clsrv/login"
  rubylib="RUBYLIB=$stodo_envpath/core"
  for d in $dirlist; do
    rubylib="$rubylib:$stodo_envpath/$d"
  done
  eval export $rubylib
}
