#!/usr/bin/env bash
# vim: ts=2 sw=2 expandtab
# Start up the stodo_server.

progname=$(basename $0)
stodo_envpath="$STODO_PATH"
. $stodo_envpath/start_up/server_setup
server=$stodo_envpath/main/init-server.rb

run() {
  cmd=$1; shift
  $RUBY_EXEC $STEXEC_PATH/$cmd "$@"
  status=$?
  if [ $status -ne 0 ]; then
    echo "command failed [$RUBY_EXEC $STEXEC_PATH/$cmd $@]" >&2
    exit $status
  fi
}

set_rubylib
run $server "$@"
