#!/usr/bin/env bash
# vim: ts=2 sw=2 expandtab
# Start up the stodo CLI client.

progname=$(basename $0)
stodo_envpath="$STODO_PATH"
client=$stodo_envpath/main/cli-client.rb

set_rubylib() {
  clsrv=client_server
  srvd=$clsrv/server
  clntd=$clsrv/client
  dirlist="facility error configuration notification specs data"
  dirlist="$dirlist coordination util attributes"
  dirlist="$dirlist domain/services/reporting external/messaging"
  dirlist="$dirlist lib/messaging domain/support"
  dirlist="$dirlist lib/util lib/util/redis external/util"
  dirlist="$dirlist $clsrv/support $clsrv/communication $clntd/main"
  rubylib="RUBYLIB=$stodo_envpath/core"
  for d in $dirlist; do
    rubylib="$rubylib:$stodo_envpath/$d"
  done
  eval export $rubylib
}

run() {
  cmd=$1; shift
  $RUBY_EXEC $STEXEC_PATH/$cmd "$@"
  status=$?
  if [ $status -ne 0 ]; then
    echo "command failed [$RUBY_EXEC $STEXEC_PATH/$cmd $@]" >&2
    exit $status
  fi
}

set_rubylib
run $client "$@"
