#!/usr/bin/env bash

progname=$(basename $0)
stodopath=$(dirname $0)
initproc=main/initial-processing.rb
notifyproc=main/ongoing-processing.rb
mktmpl=main/stodo-template.rb
report=main/report.rb
edit=main/stodo-mgmt.rb
stodo_envpath="$STODO_PATH"


help() {
    echo -e "usage: $progname <command>\n\ncommands:"
    echo -e "  new|init     look for and process new to-do items"
    echo -e "  notify       send pending notifications to-do items"
    echo -e "  combined     combine notifications with processing of new items"
    echo -e "  report       display a report of existing to-do items"
    echo -e "  del <h>...   delete targets with handles <h>, ..."
    echo -e "  temp         output a to-do item template"
}

set_rubylib() {
    moredirs="facility error configuration notification specs data"
    moredirs="$moredirs coordination"
    rubylib="RUBYLIB=$STEXEC_PATH/core"
    for d in $moredirs; do
        rubylib="$rubylib:$STEXEC_PATH/$d"
    done
}

checkpath() {
    for f in $*; do
        STEXEC_PATH=
        for p in $stodopath $stodo_envpath; do
            if [ -x "$p/$f" ]; then
                STEXEC_PATH=$p
            fi
        done
        if [ -z "$STEXEC_PATH" ]; then
            echo "Error: file $f not found"
            exit 11
        fi
    done
    if [ -z "$rubylib" ]; then
        set_rubylib
    fi
}

run() {
    cmd=$1; shift
    eval $rubylib $STEXEC_PATH/$cmd $*
}

process_new_items() {
    checkpath $initproc
    run $initproc
}

process_notifications() {
    checkpath $notifyproc
    run $notifyproc
}

do_combined_processing() {
    checkpath $initproc $notifyproc
    run $initproc
    sleep 1
    run $notifyproc
}

do_report() {
    checkpath $report
    run $report $*
}

do_edit() {
    checkpath $edit
    run $edit $*
}

make_template() {
    checkpath $mktmpl
    run $mktmpl $*
}

case $1 in
    new|init) process_new_items
        ;;
    noti*) process_notifications
        ;;
    comb*) do_combined_processing
        ;;
    rep*) do_report $*
        ;;
    del*)
      shift;
      do_edit delete $*
        ;;
    temp*) shift; make_template $*
        ;;
    *) help
        ;;
esac
